version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chirpy-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: chirpy
      POSTGRES_USER: user
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
