# request: Health check
GET http://localhost:8080/api/healthz
###

# request: Reset
POST http://localhost:8080/admin/reset
###

# request: GET users
GET http://localhost:8080/api/users
###

# request: POST users
POST http://localhost:8080/api/users
content-type: application/json

{
  "email": "usermaster@gmail.com",
  "password": "abc123"
}
###

# request: login
POST http://localhost:8080/api/login
content-type: application/json

{
  "password": "abc123",
  "email": "usermaster@gmail.com"
}

> {%
    client.global.set("auth_token", response.body.token);
    client.global.set("refresh_token", response.body.refresh_token);
%}
###

# request: POST refresh
POST http://localhost:8080/api/refresh
content-type: application/json
Authorization: Bearer {{refresh_token}}
###

# request: POST /api/chirps
POST http://localhost:8080/api/chirps
content-type: application/json
Authorization: Bearer {{auth_token}}

{
  "body": "trupm is a turd"
}
###

# request: GET chirps
GET http://localhost:8080/api/chirps
###
