# Health check
GET http://localhost:8080/api/healthz
###

# Reset
POST http://localhost:8080/admin/reset
###

# GET users
GET http://localhost:8080/api/users
###

# POST users
POST http://localhost:8080/api/users
content-type: application/json

{
  "email": "usermaster@gmail.com",
  "password": "abc123"
}
###

# login
POST http://localhost:8080/api/login
content-type: application/json

{
  "password": "abc123",
  "email": "usermaster@gmail.com",
  "expires_in_seconds": 300
}

> {%
    client.global.set("auth_token", response.body.token);
    client.global.set("user_id", response.body.user_id);
%}
###

# POST /api/chirps
POST http://localhost:8080/api/chirps
content-type: application/json
Authorization: Bearer {{auth_token}}

{
  "body": "this is a chirp!",
  "user_id": "{{user_id}}"
}
###

# GET chirps
GET http://localhost:8080/api/chirps
###
